In [2]:
import numpy as np
import pandas as pd

In [9]:
# ndarray 생성
# shap : 배열의 구조값, ndim : 차원값 확인
# 1. array functhon 사용
array1 = np.array([1,2,3])
print(type(array1))
# print(dir(array1)) # dir : 오브젝트 멤버(변수, 메소드) 목록 출력 함수
print(array1.shape)
print(array1.ndim)


<class 'numpy.ndarray'>
(3,)
1


In [10]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.T)
print(arr.transpose())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [13]:
list_2d = [[1,2,3],[4,5,6]]
print(list_2d)

[[1, 2, 3], [4, 5, 6]]


In [17]:
# 타입 변경
array_int = np.array([1,2,3])
print(array_int.dtype)
# 실수로 변환
array_float=array_int.astype('float64')
print(array_float.dtype)



int64
float64


In [21]:
seq_arr=np.arange(10)
print(seq_arr)
print(seq_arr.dtype)
print(seq_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)


In [24]:
# 2.2 zeros((행,열)) : nbarray object 생성하고 0 으로 초기화
zeros_arr = np.zeros((3,2))
print(zeros_arr)
print(zeros_arr.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [26]:
ones_arr = np.ones((3,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
arr1 = np.arange(10)
print(arr1)
arr2 = arr1.reshape(2,5)
print(arr2)
arr3 = arr1.reshape(5,2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [36]:
# reshape 유용한 기능
data_num = 1000005
arr1 = np.arange(data_num)
print(arr1)
# 5열짜지로 만들고자 한다

c_n=int(data_num/5)
print(arr1)
print(arr1.reshape(c_n,5))
print(arr1.reshape(-1,5))
print(arr1.reshape(5,-1))

[      0       1       2 ... 1000002 1000003 1000004]
[      0       1       2 ... 1000002 1000003 1000004]
[[      0       1       2       3       4]
 [      5       6       7       8       9]
 [     10      11      12      13      14]
 ...
 [ 999990  999991  999992  999993  999994]
 [ 999995  999996  999997  999998  999999]
 [1000000 1000001 1000002 1000003 1000004]]
[[      0       1       2       3       4]
 [      5       6       7       8       9]
 [     10      11      12      13      14]
 ...
 [ 999990  999991  999992  999993  999994]
 [ 999995  999996  999997  999998  999999]
 [1000000 1000001 1000002 1000003 1000004]]
[[      0       1       2 ...  199998  199999  200000]
 [ 200001  200002  200003 ...  399999  400000  400001]
 [ 400002  400003  400004 ...  600000  600001  600002]
 [ 600003  600004  600005 ...  800001  800002  800003]
 [ 800004  800005  800006 ... 1000002 1000003 1000004]]


In [46]:
arr1=np.arange(12)
print(arr1)
print(arr1.ndim, '차원')
arr2=arr1.reshape(3,4)
print(arr2.ndim, '차원')

arr3 = arr1.reshape(2,2,3)
print(arr3)
print(arr3.ndim,'차원')

arr4 = arr3.reshape(-1,4)
print(arr4)
print(arr4.ndim, '차원')

arr5=arr3.reshape(4,-1)
print(arr5)

arr6=arr3.reshape(-1)
print(arr6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1 차원
2 차원
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3 차원
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2 차원
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
arr1=np.arange(1,10)
print(arr1)
value=arr1[2]
value1=arr1[-1]
arr1[2] = 13
print(arr1)
print(value)
print(value1)
print(type(value))

[1 2 3 4 5 6 7 8 9]
[ 1  2 13  4  5  6  7  8  9]
3
9
<class 'numpy.int64'>


In [53]:
# 2차원 데이터 인덱싱
arr1d = np.arange(1,10)
print(arr1d)
arr2d = arr1d.reshape(3,3)
print(arr2d)
print(arr2d[1,2])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [56]:
arr1 = np.arange(1,10)
print(arr1)
arr3 = arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [59]:
print(arr1)
arr4=arr1[:3]
print(arr4)
arr5=arr1[3:]
print(arr5)

arr6 = arr1[:]
print(arr6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [61]:
print(arr2d)
print(arr2d[1:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


In [63]:
print(arr2d)
 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
arr1d=np.arange(1,10)
print(arr1d > 5)
print(arr1d[[False,False,False,False,False,True,True,True,True]])
print(arr1d[arr1d>5])

[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


In [68]:
# 32page
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
print(boolean_indexes)
print(arr1d[boolean_indexes]) 


[False False False False False  True  True  True  True]
[6 7 8 9]
