In [1]:
import numpy as np
import pandas as pd
titanic_df = pd.read_csv(
    '../data/titanic/train.csv'
)
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [3]:
print(titanic_df.shape) # 891행 12열
print(titanic_df.ndim)

(891, 12)
2


In [4]:
# 기본 통계값 확인 - 숫자값에 대한 통계량 표시
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
# 컬럼별 데이터 분포 확인
print(titanic_df['Pclass'].unique())
print(titanic_df['Pclass'].value_counts()) # 값들의 개수
print(titanic_df['Pclass'].value_counts()[3]) # 값들의 개수

[3 1 2]
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
491


In [6]:
print(titanic_df.shape)
print('타이타닉 데이터 건수 :', titanic_df.shape[0]) # DataFrame 건수(ROW수) => shape : tuple
print(titanic_df['Embarked'].value_counts()) # dropna=True default
print(titanic_df['Embarked'].value_counts(dropna=False))

(891, 12)
타이타닉 데이터 건수 : 891
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


In [7]:
# DataFrame과 리스트, 딕셔너리, ndarray 상호 변환
# ndarray, list, dict => DataFrame
column_name = ['col1'] # 컬럼명 변수
list1 = [1, 2, 3] # 리스트 생성, shape 없다
arr1 = np.array(list1) # ndarray object 생성, shape 존재
print('arr1 shape :', arr1.shape, ', arr1 dim :', arr1.ndim)
# 1. 리스트로 DataFrame 생성
df_list1 = pd.DataFrame(
      data=list1            # values => ndarray
    , columns=column_name   # columns
)
print(df_list1)

# ndarray => DataFrame 생성
df_arr1 = pd.DataFrame(
      data=arr1             # arr1 ndarray => ndarray
    , columns=column_name
)
print(df_arr1)

arr1 shape : (3,) , arr1 dim : 1
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [8]:
# 2차원 데이터(리스트, ndarray) => DataFrame 생성
# 2행 X 3열 list
list2d = [
      [1, 2, 3]
    , [11, 12, 13]
]
print(list2d)
# list => ndaarray
arr2d = np.array(list2d)
print(arr2d)

columns = ['col1', 'col2', 'col3']
# list => DataFrame
df_list2 = pd.DataFrame(
      data=list2d
    , columns=columns
)
print(df_list2)

# ndarray => DataFrame
df_arr2d = pd.DataFrame(
      data = arr2d
    , columns=columns
)
print(df_arr2d)

[[1, 2, 3], [11, 12, 13]]
[[ 1  2  3]
 [11 12 13]]
   col1  col2  col3
0     1     2     3
1    11    12    13
   col1  col2  col3
0     1     2     3
1    11    12    13


In [9]:
# Dict => DataFrame
# aaa = dict() # new 될때 __init__() 호출
# print(type(aaa))
dict_ = {
      'col1': [1, 11] # key => 컬럼명, value => 컬럼의 값으로 들어간다
    , 'col2': [2, 12]
    , 'col3': [3, 13]
}
print(dict_)
df_dict = pd.DataFrame(
    data=dict_
)
df_dict

{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}


col1  col2  col3
0     1     2     3
1    11    12    13

In [10]:
# DataFrame : 데이터 전처리 => ndarray(values) : 머신러닝, 딥러닝
arr3 = df_dict.values # attribute
print(arr3)
# ndarray : shape, ndim
print(arr3.shape)

[[ 1  2  3]
 [11 12 13]]
(2, 3)


In [11]:
# DataFrame => Dict
dict3 = df_dict.to_dict()
print(dict_) # dictionary
print(dict3)
dict3 = df_dict.to_dict('list')
print(dict3)

{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}
{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 12}, 'col3': {0: 3, 1: 13}}
{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}


In [12]:
# DataFrame => list 변환
# df_dict.values : ndarray => tolist() => list 추출
list3 = df_dict.values.tolist()
print(list3)

[[1, 2, 3], [11, 12, 13]]


In [13]:
# DataFrame의 컬럼 데이터 세트 생성과 수정
# 타이타닉 데이터 활용
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [14]:
# 새로운 컬럼 추가 : 'Age_0' 컬럼 추가
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [15]:
# 새로운 컬럼 추가 : 계산해서 대입 => 원래 나이 * 10
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0      220.0  
1      0          PC 17599  71.2833   C85        C      0      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0

In [16]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
 12  Age_0        891 non-null    int64  
 13  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB


In [17]:
aaa = np.nan * 10
print(aaa)

nan


In [18]:
# 형제, 배우자, 동승자(SibSp), 가족(부모, 자식, Parch) 의 합 : 가족인원수
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [19]:
# DataFrame 데이터(행, 열) 삭제
titanic_drop_df = titanic_df.drop( # 컬럼 삭제
      'Age_0'
    , axis=1
    , inplace=False # 원본 반영이 안된다, 원본 보호하겠다
)
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_0', 'Age_by_10',
       'Family_No'],
      dtype='object')

In [20]:
df = pd.DataFrame(
    data={
          'a': [1]
        , 'b': [11]
    }
)
df

a   b
0  1  11

In [21]:
a_df = df.drop('a', axis=1, inplace=False)
print(a_df)
print(df)

    b
0  11
   a   b
0  1  11


In [22]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   
3      0            113803  53.1000  C123        S      0      350.0   
4      0            373450   8.0500   NaN        S      0      350.0   

   Family_No  
0          2  
1          2  
2          1  
3          2  
4          1

In [23]:
# 여러개 컬럼 삭제
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print(titanic_df.head(1))
print(drop_result)

   PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S  
None


In [24]:
# 행 삭제


In [25]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [26]:
# pandas 출력 결과 환경 설정
# pd.set_option('환경설정 키', value)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)

In [27]:
# row drop
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [28]:
# Index object
titanic_df = pd.read_csv('../data/titanic/train.csv')
print(titanic_df.head(2))
# Index object 추출
indexes = titanic_df.index
print(indexes)
print(type(indexes.values))
print(indexes.values[:5])

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C
RangeIndex(start=0, stop=891, step=1)
<class 'numpy.ndarray'>
[0 1 2 3 4]


In [29]:
# Series object
series_fair = titanic_df['Fare'] # 컬럼 하나를 추출 => 시리즈 반환된다
print(type(series_fair))

<class 'pandas.core.series.Series'>


In [30]:
print(series_fair.max()) # 최대값 추출
print(series_fair.min()) # 최소값 추출
print(series_fair.sum()) # series object sum method : 합 계산
print(sum(series_fair)) # 내장함수

512.3292
0.0
28693.9493
28693.949299999967


In [31]:
series_fair[:5]

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [32]:
(series_fair + 3)[:5]

0    10.2500
1    74.2833
2    10.9250
3    56.1000
4    11.0500
Name: Fare, dtype: float64

In [33]:
# reset_index() : index 다시 숫자 인덱스(0부터 시작) 초기화
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [34]:
# 실습
print('#### before reset_index ####')
value_counts_ = titanic_df['Pclass'].value_counts() # return Series
print(value_counts_)
print('#### after reset_index ####')
new_value_counts = value_counts_.reset_index(inplace=False)
print(new_value_counts)

#### before reset_index ####
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
#### after reset_index ####
   Pclass  count
0       3    491
1       1    216
2       2    184


In [35]:
# 데이터 선택과 걸러내기
# 선택 문제점 : DataFrame => [] 연산자 => [컬럼/인덱스]
# 단일 컬럼 데이터 추출 : Pclass 컬럼 추출
print(titanic_df['Pclass'].head(3))
# 여러 컬럼 추출(슬라이싱) => 팬시색인 : Survived, Pclass
print(titanic_df[['Survived', 'Pclass']].head(3))
# [숫자인덱스]
print(titanic_df[titanic_df.columns[0]]) # 컬럼명이 0이라는 컬럼 선택
print(titanic_df.columns[0]) # PassengerId

0    3
1    1
2    3
Name: Pclass, dtype: int64
   Survived  Pclass
0         0       3
1         1       1
2         1       3
0        1
1        2
2        3
3        4
4        5
      ... 
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64
PassengerId


In [36]:
# [컬럼명], [[컬럼명,컬럼명]] : 컬럼 접근
# [숫자인덱스:숫자인덱스] : 행추출
titanic_df[:2]
# [행,열]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [37]:
# 불린 인덱싱
# Pclass 가 3등급인 승객 데이터(행) 추출
titanic_df[titanic_df['Pclass'] == 3].head()

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0          330877   8.4583   NaN        Q
7            8         0       3  Palsson, Ma...    male   2.0      3      1          349909  21.0750   NaN        S

In [38]:
# iloc[], loc[] : 행 접근, 컬럼 접근
data = {
      'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobe']
    , 'Year': [2011, 2016, 2015, 2015]
    , 'Gender': ['Male', 'Female', 'Male', 'Male']
}

In [39]:
data_df = pd.DataFrame(
      data=data
    , index=['one', 'two', 'three', 'four']
)
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four      Soobe  2015    Male

In [40]:
# iloc[] : RangeIndex 접근, 숫자인덱스 접근
data_df.iloc[0, 0] # iloc[0행, 0열]
# data_df.iloc[0, 'Name'] error
# data_df.iloc['one', 0] error

'Chulmin'

In [41]:
# 실습
#       Name	    Year	Gender
# one	Chulmin	    2011	Male
# two	Eunkyung	2016	Female
# three	Jinwoong	2015	Male
# four	Soobe	    2015	Male
print(data_df.iloc[1, 0])
print(data_df.iloc[2, 1])
print(data_df.iloc[:2, [0, 1]]) # [행, 열] : 행 => :2
print(data_df.iloc[0:2, 0:3])
print(data_df.iloc[:]) # 모든 행, 모든 컬럼 추출
print(data_df.iloc[:, :]) # 모든 행, 모든 컬럼 추출

Eunkyung
2015
         Name  Year
one   Chulmin  2011
two  Eunkyung  2016
         Name  Year  Gender
one   Chulmin  2011    Male
two  Eunkyung  2016  Female
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four      Soobe  2015    Male
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four      Soobe  2015    Male


In [42]:
# - 인덱스
print(data_df.iloc[:, -1]) # 모든행, 열:끝
print(data_df['Gender'])
print(data_df.iloc[:, :-1])

one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object
one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object
           Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four      Soobe  2015


In [43]:
# loc[] : 네임드 인덱스 사용
print(data_df.loc['one', 'Name'])
# print(data_df.loc[0, 'Name']) error
print(data_df.loc['one':'two', 'Name']) # 'one':'two' : 행슬라이싱

Chulmin
one     Chulmin
two    Eunkyung
Name: Name, dtype: object


In [44]:
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four      Soobe  2015    Male

In [45]:
# loc[] 연습
print(data_df.loc['one':'two', ['Name','Gender']])
print(data_df.loc['one':'three', 'Name':'Gender'])
print(data_df.loc[:]) # 행 선택
print(data_df[data_df.Year >= 2014]) # 

         Name  Gender
one   Chulmin    Male
two  Eunkyung  Female
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four      Soobe  2015    Male
           Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four      Soobe  2015    Male


In [46]:
# 불린 인덱싱
titanic_df = pd.read_csv('../data/titanic/train.csv')
titanic_df.head()

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S

In [47]:
# 나이가 60이상인 승객 filter
# (titanic_df['Age'] > 60).value_counts()
# titanic_df[titanic_df['Age'] > 60] # 22개 행 추출 DataFrame
titanic_df[titanic_df['Age'] > 60]['Survived'].value_counts()
# 60세 이상 승객 가운데 생존한 승객 데이터 추출
# titanic_df[titanic_df['Age'] > 60][titanic_df['Survived'] == 1]
titanic_df[(titanic_df['Age'] > 60) & (titanic_df['Survived'] == 1)]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502  77.9583    D7        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134   9.5875   NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752  10.5000   NaN        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042  30.0000   A23        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572  80.0000   B28      NaN

In [48]:
import numpy as np
import pandas as pd

titanic_df = pd.read_csv(
    '../data/titanic/train.csv'
)
titanic_df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [49]:
titanic_df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [50]:
# (lambda x : x ** 2)(3) 일회성
lambda_square = lambda x : x ** 2
print(lambda_square)
print(lambda_square(3))

<function <lambda> at 0x000001B5818C53F0>
9


In [51]:
# map() 내장함수 :
a = [1, 2, 3] # list
def get_square(x):
    return x ** 2

for num in a:
    print(get_square(num))

# squares = map(lambda x : x ** 2, a)
# print(list(squares))

1
4
9


In [52]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df[['Age', 'Age_cat']]
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      609
Elderly    199
Child       83
Name: count, dtype: int64

In [54]:
# 연속적데이터(Age)를 카테고리(범주)형 변환 작업
def get_cate(age): # 나이 개별 데이터 입력
    cat = '' # 대입을 해 놓아야 변수가 생성
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else: cat = 'Elderly' # old
    
    return cat

In [56]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_cate(x))
titanic_df[['Age', 'Age_cat']].head()

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult